export const dataFields = {
  fields: [
    "firstName",
    "middleName",
    "lastName",
    "gender",
    "location",
    "workPhone",
    "mobilePhone",
    "workEmail",
    "department",
    "division",
    "id",
    "jobTitle",
    "photoUrl",
    "photoUploaded",
    "supervisor",
  ],
  title: "EmployeeList",
};
