import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/signin">SignIn</Link>
        </li>
        <li>
          <Link to="/employeedirectory">EmployeeDirectory</Link>
        </li>
        <li>
          <Link to="/createemployee">CreateEmployee</Link>
        </li>
        <li>
          <Link to="/employeelist">EmployeeList</Link>
        </li>
        <li>
          <Link to="/addemployee">AddEmployee</Link>
        </li>
        <li>
          <Link to="/createbulkemployees">Createbulkemployees</Link>
        </li>
        <li>
          <Link to="/employeelistfilter">EmployeeListFilter</Link>
        </li>
        <li>
          <Link to="/documents">Documents</Link>
        </li>
        <li>
          <Link to="/filesone">FilesOne</Link>
        </li>
        <li>
          <Link to="/files">Files</Link>
        </li>
        <li>
          <Link to="/permission">Permission</Link>
        </li>
        <li>
          <Link to="/spacemanagement">SpaceManagement</Link>
        </li>
        <li>
          <Link to="/viewspace">ViewSpace</Link>
        </li>
        <li>
          <Link to="/bookspacedaily">BookSpaceDaily</Link>
        </li>
        <li>
          <Link to="/bookspaceweekly">BookSpaceWeekly</Link>
        </li>
        <li>
          <Link to="/bookspacemonthly">BookSpaceMonthly</Link>
        </li>
        <li>
          <Link to="/viewbooking">ViewBooking</Link>
        </li>
        <li>
          <Link to="/mybooking">MyBooking</Link>
        </li>
        <li>
          <Link to="/mybookingfilter">MyBookingFilter</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
